export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';

export const CART_FROM_LOCAL_STORAGE = 'CART_FROM_LOCAL_STORAGE';

export const LOAD_BOOKS_LOADING = 'LOAD_BOOKS_LOADING';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_ERROR = 'LOAD_BOOKS_ERROR';
